# Header
menu:
  Home: /
  Archives: /archives
  About: /About
rss: /atom.xml

menu_icon:
  Home: fa-home
  Archives: fa-archive
  About: fa-user

# Content
excerpt_link: Read More
fancybox: true

#your personal image
your_img: https://avatars0.githubusercontent.com/u/1271101?v=3&s=150 

# Miscellaneous
google_analytics: 
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:
duoshuo_shortname: A Blog
